# Generated by Django 4.2.1 on 2023-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(default=None, upload_to="uploads/"),
        ),
    ]
