# Generated by Django 4.2.1 on 2023-06-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_file_file_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_token',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
